"""Inverse mapping: tongue keypoints -> muscle activations.

Given DLC dorsal-chain keypoints observed in ultrasound, estimate the 23-dim
muscle activation percentages that produced that tongue shape. Pure NumPy
ridge regression trained on a synthetic dataset generated by the forward
biomechanical solver.

Optimisation choice
-------------------
Option A: batched PyTorch forward solver.

The naive approach of calling the NumPy ``solve_equilibrium`` 5000 times is
~320 s on this machine (65 ms/call at 100 iters). We port the Jacobi
relaxation in ``solver.py`` to PyTorch with a leading batch dimension ``B``
so all samples are solved in parallel on the GPU (CPU fallback). The main
bottleneck in NumPy is the Python loop; vectorising across the batch is a
dense matmul/scatter problem that fits GPU workloads well.

We picked Option A over Option B (neural surrogate) because:
* A is exact — the batched solver is numerically equivalent to the NumPy
  solver (parity test with ``atol=1e-4`` before dataset generation).
* No approximation error to characterise.
* Target 5000 samples in <2 s on GPU / <10 s on CPU — comfortably met.

The module still uses the original NumPy ``solve_equilibrium`` as the
source-of-truth for parity tests and as a CPU fallback if Torch is missing.

See ``docs/plans/biomech-inverse-mapping.md`` for the full design.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.interpolate import interp1d

from sigflow.biomech.s3d_parser import S3DModel
from sigflow.biomech.solver import solve_equilibrium

try:  # torch is in the dev group but may not always be installed
    import torch

    _TORCH_AVAILABLE = True
except ImportError:  # pragma: no cover - torch always present in this project
    _TORCH_AVAILABLE = False


__all__ = [
    "InverseMapping",
    "midline_indices",
    "resample_curve",
    "generate_synthetic_dataset",
    "fit_ridge",
    "predict_activations",
    "save_inverse_mapping",
    "load_inverse_mapping",
    "batched_forward_solve",
    "build_inverse_mapping",
]


# ---------------------------------------------------------------------------
# Midline extraction and resampling
# ---------------------------------------------------------------------------


def midline_indices(
    positions: np.ndarray,
    fixing: np.ndarray,
    polygons: list[np.ndarray],
) -> np.ndarray:
    """Ordered atom indices tracing the midsagittal surface curve.

    The .s3d half-model is closed off by a cap of triangles whose vertices
    all lie on the symmetry plane. The outline of that cap is a clean 1D
    closed loop — exactly what we want for the midsagittal curve. We

    1. collect all polygons whose vertices are all on the symmetry plane
       (``fixing == 2``);
    2. count edge multiplicities inside that sub-mesh — boundary edges
       appear exactly once (interior edges appear twice);
    3. build an adjacency list from the boundary edges;
    4. walk the cycle from its lowest-variance-axis extreme point.

    If the polygon cap walk cannot be formed (defensive fallback), drop
    back to a greedy nearest-neighbour walk across all symmetric surface
    atoms.

    Args:
        positions: (N, 3) atom positions.
        fixing: (N,) fixing flags (0=free, 1=static, 2=symmetric).
        polygons: list of polygon faces (each an int array of atom indices).

    Returns:
        (K,) int64 array of atom indices, ordered along the curve.
    """
    sym_atoms = np.where(fixing == 2)[0]
    if sym_atoms.size == 0:
        raise ValueError("No symmetric atoms (fixing == 2) in the model.")
    sym_set = set(int(i) for i in sym_atoms)

    # Count edges that lie entirely inside the symmetric-only polygon cap.
    edge_count: dict[tuple[int, int], int] = {}
    for face in polygons:
        verts = [int(v) for v in face]
        if not verts or not all(v in sym_set for v in verts):
            continue
        n = len(verts)
        for i in range(n):
            u, v = verts[i], verts[(i + 1) % n]
            e = (u, v) if u < v else (v, u)
            edge_count[e] = edge_count.get(e, 0) + 1

    boundary = [e for e, c in edge_count.items() if c == 1]

    if boundary:
        adj: dict[int, list[int]] = {}
        for u, v in boundary:
            adj.setdefault(u, []).append(v)
            adj.setdefault(v, []).append(u)

        # All degrees should be 2 on a clean cycle. If not, fall back below.
        if all(len(n) == 2 for n in adj.values()):
            # Project onto 2D for start-point selection.
            cand = np.array(sorted(adj.keys()), dtype=np.int64)
            pts = positions[cand]
            frozen_axis = int(np.argmin(pts.var(axis=0)))
            keep = [a for a in range(3) if a != frozen_axis]
            pts2d = pts[:, keep]
            start_axis = int(np.argmax(pts2d.var(axis=0)))
            start = int(cand[np.argmin(pts2d[:, start_axis])])

            order_list: list[int] = [start]
            visited = {start}
            prev: int | None = None
            curr = start
            while True:
                nexts = [x for x in adj[curr] if x != prev]
                if not nexts:
                    break
                nxt = nexts[0]
                if nxt == start:
                    break
                if nxt in visited:
                    break
                order_list.append(nxt)
                visited.add(nxt)
                prev = curr
                curr = nxt
            return np.asarray(order_list, dtype=np.int64)

    # Fallback: greedy NN walk over all sym atoms that appear in any polygon.
    in_polygon = np.zeros(len(positions), dtype=bool)
    for face in polygons:
        if len(face) == 0:
            continue
        in_polygon[np.asarray(face, dtype=np.int64)] = True
    candidate_mask = (fixing == 2) & in_polygon
    candidates = np.where(candidate_mask)[0]
    if candidates.size == 0:
        raise ValueError("No midline atoms found (fixing == 2 & in polygon).")

    pts = positions[candidates]
    variances = pts.var(axis=0)
    frozen_axis = int(np.argmin(variances))
    keep = [a for a in range(3) if a != frozen_axis]
    pts2d = pts[:, keep]

    axis_var = pts2d.var(axis=0)
    start_axis = int(np.argmax(axis_var))
    start_local = int(np.argmin(pts2d[:, start_axis]))

    n = len(candidates)
    visited_arr = np.zeros(n, dtype=bool)
    order = np.empty(n, dtype=np.int64)
    visited_arr[start_local] = True
    order[0] = start_local
    current = start_local
    for step in range(1, n):
        diff = pts2d - pts2d[current]
        d2 = np.einsum("ij,ij->i", diff, diff)
        d2[visited_arr] = np.inf
        nxt = int(np.argmin(d2))
        order[step] = nxt
        visited_arr[nxt] = True
        current = nxt

    return candidates[order]


def resample_curve(positions: np.ndarray, n_out: int = 11) -> np.ndarray:
    """Arc-length resample a 2D polyline to ``n_out`` equidistant samples.

    Args:
        positions: (K, 2) ordered points along a curve.
        n_out: number of output samples (default 11).

    Returns:
        (n_out, 2) resampled points.
    """
    if positions.ndim != 2 or positions.shape[1] != 2:
        raise ValueError(f"Expected (K, 2) array, got {positions.shape}.")
    if len(positions) < 2:
        raise ValueError("Need at least 2 points to resample a curve.")

    seg = np.linalg.norm(np.diff(positions, axis=0), axis=1)
    arc = np.concatenate([[0.0], np.cumsum(seg)])
    total = arc[-1]
    if total <= 0:
        raise ValueError("Degenerate curve (zero total length).")
    u = arc / total  # [0, 1]

    # scipy interp1d on each coordinate (kind='linear' for stability).
    t = np.linspace(0.0, 1.0, n_out)
    fx = interp1d(u, positions[:, 0], kind="linear", assume_sorted=True)
    fy = interp1d(u, positions[:, 1], kind="linear", assume_sorted=True)
    return np.stack([fx(t), fy(t)], axis=1)


# ---------------------------------------------------------------------------
# Batched PyTorch forward solver
# ---------------------------------------------------------------------------


def batched_forward_solve(
    model: S3DModel,
    activations: "np.ndarray | torch.Tensor",
    max_iter: int = 100,
    device: "str | None" = None,
) -> np.ndarray:
    """Batched Jacobi relaxation forward solver.

    Numerically equivalent to running ``solve_equilibrium`` B times. All
    tensors gain a leading batch dimension. Uses CUDA if available.

    Args:
        model: parsed S3D model.
        activations: (B, K) muscle activation percentages.
        max_iter: relaxation iterations (default 100, same as NumPy solver).
        device: torch device name. Defaults to 'cuda' if available, else 'cpu'.

    Returns:
        (B, N, 3) equilibrium positions as float64 numpy array.
    """
    if not _TORCH_AVAILABLE:
        raise RuntimeError("PyTorch is required for batched_forward_solve.")

    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    dev = torch.device(device)
    dtype = torch.float64

    acts = torch.as_tensor(np.asarray(activations, dtype=np.float64), dtype=dtype, device=dev)
    if acts.ndim != 2:
        raise ValueError(f"activations must be (B, K), got shape {tuple(acts.shape)}.")
    B, K = acts.shape
    if K != model.n_muscles:
        raise ValueError(
            f"activations K={K} != model.n_muscles={model.n_muscles}"
        )

    n_atoms = model.n_atoms
    # Rest positions broadcast to (B, N, 3)
    base_pos = torch.as_tensor(model.positions, dtype=dtype, device=dev)
    pos = base_pos.unsqueeze(0).expand(B, -1, -1).contiguous()

    # Strut connectivity (shared across batch)
    strut_pairs = torch.as_tensor(model.strut_pairs, dtype=torch.long, device=dev)
    a1 = strut_pairs[:, 0]
    a2 = strut_pairs[:, 1]

    rest = torch.as_tensor(model.rest_lengths, dtype=dtype, device=dev)
    er = torch.as_tensor(model.elasticity_r, dtype=dtype, device=dev)
    ec = torch.as_tensor(model.elasticity_c, dtype=dtype, device=dev)
    strut_muscles = torch.as_tensor(model.strut_muscles, dtype=torch.long, device=dev)
    fixing = torch.as_tensor(model.fixing, dtype=torch.int32, device=dev)

    M = strut_pairs.shape[0]
    has_muscle = strut_muscles >= 0
    musc_idx = strut_muscles.clamp(min=0)  # safe indices (masked later)

    # Per-batch target lengths and elasticities over struts.
    # acts[:, musc_idx] -> (B, M), same broadcasting rule as NumPy advanced indexing
    muscle_pct = acts[:, musc_idx]  # (B, M)
    # target_lengths[i, j] = max(rest[j] * pct/100, 1.0) if strut has muscle
    scaled = rest.unsqueeze(0) * (muscle_pct / 100.0)
    scaled = torch.clamp(scaled, min=1.0)
    rest_b = rest.unsqueeze(0).expand(B, -1)
    target = torch.where(has_muscle.unsqueeze(0), scaled, rest_b)

    ratio = target / rest_b
    elast_active = (er.unsqueeze(0) - ec.unsqueeze(0)) * ratio + ec.unsqueeze(0)
    er_b = er.unsqueeze(0).expand(B, -1)
    elasticity = torch.where(has_muscle.unsqueeze(0), elast_active, er_b)  # (B, M)

    free_mask = (fixing == 0).unsqueeze(0)  # (1, N)
    sym_mask = (fixing == 2).unsqueeze(0)  # (1, N)

    # Pre-allocate scratch buffers.
    forces = torch.empty((B, n_atoms, 3), dtype=dtype, device=dev)
    weights = torch.empty((B, n_atoms), dtype=dtype, device=dev)

    # Axis to zero out when updating symmetric atoms: keep the two axes that
    # span the symmetry plane free, zero the normal.
    if model.symmetry_axes == 0:  # XY plane: freeze Z
        freeze_axis = 2
    elif model.symmetry_axes == 1:  # XZ plane: freeze Y
        freeze_axis = 1
    else:  # YZ plane: freeze X
        freeze_axis = 0

    # index_add needs LongTensor indices
    a1_b = a1.unsqueeze(0).expand(B, -1)
    a2_b = a2.unsqueeze(0).expand(B, -1)

    for _ in range(max_iter):
        p1 = pos.gather(1, a1_b.unsqueeze(-1).expand(-1, -1, 3))  # (B, M, 3)
        p2 = pos.gather(1, a2_b.unsqueeze(-1).expand(-1, -1, 3))
        diff = p1 - p2  # (B, M, 3)
        dist = torch.linalg.norm(diff, dim=2)  # (B, M)
        dist = torch.clamp(dist, min=1e-10)

        b = (dist - target) / dist / 2.0  # (B, M)
        active = b > 0
        b_e = torch.where(active, b * elasticity, torch.zeros_like(b))  # (B, M)
        w_e = torch.where(active, elasticity, torch.zeros_like(elasticity))  # (B, M)

        force_vec = diff * b_e.unsqueeze(-1)  # (B, M, 3)

        forces.zero_()
        weights.zero_()
        # Scatter forces: atom a1 -= force_vec, a2 += force_vec.
        forces.scatter_add_(1, a1_b.unsqueeze(-1).expand(-1, -1, 3), -force_vec)
        forces.scatter_add_(1, a2_b.unsqueeze(-1).expand(-1, -1, 3), force_vec)
        weights.scatter_add_(1, a1_b, w_e)
        weights.scatter_add_(1, a2_b, w_e)

        nonzero = weights > 0
        safe_w = torch.where(nonzero, weights, torch.ones_like(weights))
        forces = forces / safe_w.unsqueeze(-1)
        forces = torch.where(nonzero.unsqueeze(-1), forces, torch.zeros_like(forces))

        # Free atoms: full update.
        pos = torch.where(free_mask.unsqueeze(-1), pos + forces, pos)

        # Symmetric atoms: zero the frozen axis in the update.
        sym_force = forces.clone()
        sym_force[..., freeze_axis] = 0.0
        pos = torch.where(sym_mask.unsqueeze(-1), pos + sym_force, pos)

    return pos.detach().cpu().numpy()


def _parity_check_batched_vs_numpy(
    model: S3DModel,
    n_samples: int = 4,
    atol: float = 1e-4,
    rng: np.random.Generator | None = None,
) -> tuple[bool, float]:
    """Run the batched torch solver and the NumPy solver on the same
    activations and compare. Returns (passed, max_abs_diff)."""
    if rng is None:
        rng = np.random.default_rng(0)
    acts = rng.uniform(40.0, 100.0, size=(n_samples, model.n_muscles))

    torch_out = batched_forward_solve(model, acts, max_iter=100)

    np_out = np.empty_like(torch_out)
    for i in range(n_samples):
        np_out[i] = solve_equilibrium(
            positions=model.positions,
            strut_pairs=model.strut_pairs,
            rest_lengths=model.rest_lengths,
            elasticity_r=model.elasticity_r,
            elasticity_c=model.elasticity_c,
            strut_muscles=model.strut_muscles,
            fixing=model.fixing,
            muscle_pcts=acts[i],
            max_iter=100,
            symmetry_axes=model.symmetry_axes,
            symmetry_coord=model.symmetry_coord,
        )

    diff = np.abs(torch_out - np_out)
    return bool(diff.max() <= atol), float(diff.max())


# ---------------------------------------------------------------------------
# Synthetic dataset generation
# ---------------------------------------------------------------------------


def generate_synthetic_dataset(
    model: S3DModel,
    n_samples: int = 5000,
    n_keypoints: int = 11,
    activation_low: float = 40.0,
    activation_high: float = 100.0,
    max_iter: int = 100,
    seed: int | None = 0,
    batch_size: int = 256,
    use_torch: bool = True,
    rest_positions: np.ndarray | None = None,
    midline_atoms: np.ndarray | None = None,
    verbose: bool = False,
) -> tuple[np.ndarray, np.ndarray]:
    """Run the forward solver n_samples times on random activations.

    For each sample: draw activations in [activation_low, activation_high],
    solve forward, extract midline atoms, resample to ``n_keypoints``,
    compute displacement from rest pose, flatten to 22-dim.

    Args:
        model: parsed S3D model.
        n_samples: number of samples to generate.
        n_keypoints: resampled midline length (default 11).
        activation_low: lower bound on activation percentages.
        activation_high: upper bound on activation percentages.
        max_iter: solver iterations.
        seed: RNG seed (None -> random).
        batch_size: torch batch size (ignored if use_torch=False).
        use_torch: use batched torch solver (default True).
        rest_positions: optional precomputed rest equilibrium positions. If
            None, solved from activations=100.
        midline_atoms: optional precomputed midline atom indices. If None,
            computed from the rest positions.
        verbose: print progress.

    Returns:
        X: (n_samples, n_keypoints * 2) displacement vectors.
        Y: (n_samples, model.n_muscles) activations.
    """
    rng = np.random.default_rng(seed)
    K = model.n_muscles

    # Rest pose: solve at 100% everywhere.
    if rest_positions is None:
        rest_positions = solve_equilibrium(
            positions=model.positions,
            strut_pairs=model.strut_pairs,
            rest_lengths=model.rest_lengths,
            elasticity_r=model.elasticity_r,
            elasticity_c=model.elasticity_c,
            strut_muscles=model.strut_muscles,
            fixing=model.fixing,
            muscle_pcts=np.full(K, 100.0),
            max_iter=max_iter,
            symmetry_axes=model.symmetry_axes,
            symmetry_coord=model.symmetry_coord,
        )

    if midline_atoms is None:
        midline_atoms = midline_indices(rest_positions, model.fixing, model.polygons)

    # Determine frozen axis from rest midline (should match the symmetry
    # plane normal).
    pts_rest = rest_positions[midline_atoms]
    frozen_axis = int(np.argmin(pts_rest.var(axis=0)))
    keep_axes = [a for a in range(3) if a != frozen_axis]

    rest_keypoints = resample_curve(pts_rest[:, keep_axes], n_keypoints)

    # Sample all activations up front.
    Y = rng.uniform(activation_low, activation_high, size=(n_samples, K))

    X = np.empty((n_samples, n_keypoints * 2), dtype=np.float64)

    if use_torch and _TORCH_AVAILABLE:
        t0 = time.perf_counter()
        for start in range(0, n_samples, batch_size):
            end = min(start + batch_size, n_samples)
            acts_batch = Y[start:end]
            pos_batch = batched_forward_solve(model, acts_batch, max_iter=max_iter)
            for i in range(end - start):
                pts = pos_batch[i, midline_atoms][:, keep_axes]
                kps = resample_curve(pts, n_keypoints)
                X[start + i] = (kps - rest_keypoints).reshape(-1)
            if verbose:
                elapsed = time.perf_counter() - t0
                print(f"  [{end}/{n_samples}] {elapsed:.2f}s")
    else:
        t0 = time.perf_counter()
        for i in range(n_samples):
            pos = solve_equilibrium(
                positions=model.positions,
                strut_pairs=model.strut_pairs,
                rest_lengths=model.rest_lengths,
                elasticity_r=model.elasticity_r,
                elasticity_c=model.elasticity_c,
                strut_muscles=model.strut_muscles,
                fixing=model.fixing,
                muscle_pcts=Y[i],
                max_iter=max_iter,
                symmetry_axes=model.symmetry_axes,
                symmetry_coord=model.symmetry_coord,
            )
            pts = pos[midline_atoms][:, keep_axes]
            kps = resample_curve(pts, n_keypoints)
            X[i] = (kps - rest_keypoints).reshape(-1)
            if verbose and (i + 1) % 500 == 0:
                elapsed = time.perf_counter() - t0
                print(f"  [{i + 1}/{n_samples}] {elapsed:.2f}s")

    return X, Y


# ---------------------------------------------------------------------------
# Ridge regression (pure NumPy)
# ---------------------------------------------------------------------------


def fit_ridge(
    X: np.ndarray, Y: np.ndarray, alpha: float = 1.0
) -> tuple[np.ndarray, np.ndarray]:
    """Closed-form ridge regression with unregularised bias.

    Fits ``Y ~ X W + b`` by augmenting X with a bias column, regularising
    only the weight block (not the bias).

    Args:
        X: (n, d) input features.
        Y: (n, k) targets.
        alpha: ridge strength (default 1.0).

    Returns:
        W: (d, k) weight matrix.
        b: (k,) bias vector.
    """
    X = np.asarray(X, dtype=np.float64)
    Y = np.asarray(Y, dtype=np.float64)
    n, d = X.shape
    if Y.shape[0] != n:
        raise ValueError(f"X n={n} != Y n={Y.shape[0]}")

    # Append bias column of ones.
    X_aug = np.concatenate([X, np.ones((n, 1), dtype=np.float64)], axis=1)  # (n, d+1)
    # Regularisation matrix: alpha * I but with 0 on the bias diagonal.
    reg = alpha * np.eye(d + 1, dtype=np.float64)
    reg[-1, -1] = 0.0

    A = X_aug.T @ X_aug + reg  # (d+1, d+1)
    B = X_aug.T @ Y  # (d+1, k)
    coeffs = np.linalg.solve(A, B)  # (d+1, k)
    W = coeffs[:-1]  # (d, k)
    b = coeffs[-1]  # (k,)
    return W, b


def predict_activations(
    keypoint_displacements: np.ndarray, W: np.ndarray, b: np.ndarray
) -> np.ndarray:
    """Predict clipped activation vector from displacement features.

    Args:
        keypoint_displacements: (d,) or (n, d) displacement features.
        W: (d, k) weight matrix.
        b: (k,) bias.

    Returns:
        Activations clipped to [0, 100].
    """
    out = keypoint_displacements @ W + b
    np.clip(out, 0.0, 100.0, out=out)
    return out


# ---------------------------------------------------------------------------
# Persistable data structure
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InverseMapping:
    """Trained inverse keypoint -> activation mapping."""

    W: np.ndarray  # (n_keypoints * 2, n_muscles)
    b: np.ndarray  # (n_muscles,)
    rest_keypoints: np.ndarray  # (n_keypoints, 2)
    midline_indices: np.ndarray  # atom indices on the midline
    frozen_axis: int  # which 3D axis is the symmetry-plane normal
    muscle_names: list[str]
    n_keypoints: int
    alpha: float


def save_inverse_mapping(mapping: InverseMapping, path: str | Path) -> None:
    """Serialise an InverseMapping to a .npz archive."""
    path = Path(path)
    np.savez(
        path,
        W=mapping.W,
        b=mapping.b,
        rest_keypoints=mapping.rest_keypoints,
        midline_indices=mapping.midline_indices,
        frozen_axis=np.int64(mapping.frozen_axis),
        muscle_names=np.array(mapping.muscle_names, dtype=object),
        n_keypoints=np.int64(mapping.n_keypoints),
        alpha=np.float64(mapping.alpha),
    )


def load_inverse_mapping(path: str | Path) -> InverseMapping:
    """Load an InverseMapping from a .npz archive."""
    path = Path(path)
    with np.load(path, allow_pickle=True) as data:
        return InverseMapping(
            W=data["W"],
            b=data["b"],
            rest_keypoints=data["rest_keypoints"],
            midline_indices=data["midline_indices"],
            frozen_axis=int(data["frozen_axis"]),
            muscle_names=list(data["muscle_names"]),
            n_keypoints=int(data["n_keypoints"]),
            alpha=float(data["alpha"]),
        )


# ---------------------------------------------------------------------------
# Convenience: end-to-end build
# ---------------------------------------------------------------------------


def build_inverse_mapping(
    model: S3DModel,
    n_samples: int = 5000,
    n_keypoints: int = 11,
    alpha: float = 1.0,
    activation_low: float = 40.0,
    activation_high: float = 100.0,
    max_iter: int = 100,
    seed: int | None = 0,
    use_torch: bool = True,
    batch_size: int = 256,
    verbose: bool = False,
) -> InverseMapping:
    """Train an InverseMapping end-to-end from an S3D model.

    Solves rest pose, extracts midline atoms, generates synthetic data,
    fits ridge regression.
    """
    rest_positions = solve_equilibrium(
        positions=model.positions,
        strut_pairs=model.strut_pairs,
        rest_lengths=model.rest_lengths,
        elasticity_r=model.elasticity_r,
        elasticity_c=model.elasticity_c,
        strut_muscles=model.strut_muscles,
        fixing=model.fixing,
        muscle_pcts=np.full(model.n_muscles, 100.0),
        max_iter=max_iter,
        symmetry_axes=model.symmetry_axes,
        symmetry_coord=model.symmetry_coord,
    )
    midline = midline_indices(rest_positions, model.fixing, model.polygons)
    pts_rest = rest_positions[midline]
    frozen_axis = int(np.argmin(pts_rest.var(axis=0)))
    keep_axes = [a for a in range(3) if a != frozen_axis]
    rest_keypoints = resample_curve(pts_rest[:, keep_axes], n_keypoints)

    X, Y = generate_synthetic_dataset(
        model=model,
        n_samples=n_samples,
        n_keypoints=n_keypoints,
        activation_low=activation_low,
        activation_high=activation_high,
        max_iter=max_iter,
        seed=seed,
        batch_size=batch_size,
        use_torch=use_torch,
        rest_positions=rest_positions,
        midline_atoms=midline,
        verbose=verbose,
    )
    W, b = fit_ridge(X, Y, alpha=alpha)

    return InverseMapping(
        W=W,
        b=b,
        rest_keypoints=rest_keypoints,
        midline_indices=midline,
        frozen_axis=frozen_axis,
        muscle_names=list(model.muscle_names),
        n_keypoints=n_keypoints,
        alpha=alpha,
    )
